version: "2.4"
services:
  api:
    build:
      context: .
      target: developement
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    env_file:
      - ./.env
    command: npm run start:dev
